[Fix][ammlib] use silence level onlyerr for load check to get error messages

diff --git a/ammlib b/ammlib
--- a/ammlib
+++ b/ammlib
@@ -182,7 +182,9 @@ function ammLibLoadable {
 			# try to load it in a subshell to check init
 			typeset initfunc="$(ammLibMetaInitGetName "$libname")"
 			typeset inittext=""
-			inittext="$(ammLogSilence 1; . $libfile || exit 1; if \type $initfunc >/dev/null 2>&1; then $initfunc; exit $?; else exit 0; fi;)"
+
+			# Code 98 = fail during the load (parsing error ?)
+			inittext="$(ammLogSilence onlyerr; . $libfile || exit 98; if \type $initfunc >/dev/null 2>&1; then $initfunc; exit $?; else exit 0; fi;)"
 
 			# Dont stop loading, just log error and increase return
 			if [[ $? -ne 0 ]]; then
